package com.example.ummatelemedicineapp;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;

import com.example.ummatelemedicineapp.utils.TokenManager;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.twilio.video.Camera2Capturer;
import com.twilio.video.ConnectOptions;
import com.twilio.video.LocalAudioTrack;
import com.twilio.video.LocalVideoTrack;
import com.twilio.video.RemoteAudioTrack;
import com.twilio.video.RemoteAudioTrackPublication;
import com.twilio.video.RemoteDataTrack;
import com.twilio.video.RemoteDataTrackPublication;
import com.twilio.video.RemoteParticipant;
import com.twilio.video.RemoteVideoTrack;
import com.twilio.video.RemoteVideoTrackPublication;
import com.twilio.video.Room;
import com.twilio.video.TwilioException;
import com.twilio.video.Video;
import com.twilio.video.VideoView;

import java.util.Collections;

public class VideoConsultationActivity extends BaseActivity {

    private static final int PERMISSION_REQ_ID = 22;
    private static final String[] REQUESTED_PERMISSIONS = {
            Manifest.permission.RECORD_AUDIO,
            Manifest.permission.CAMERA
    };

    // IMPORTANT: Access tokens should be generated by a backend server.
    // For testing, ensure each participant uses a token with a DIFFERENT identity.
    private String accessToken = ""; // Will be fetched dynamically
    private String roomName = "TelemedicineRoom";
    private String userIdentity = "User_" + System.currentTimeMillis();
    private Room room;
    private LocalAudioTrack localAudioTrack;
    private LocalVideoTrack localVideoTrack;

    private VideoView localVideoView;
    private VideoView remoteVideoView;
    private TextView tvStatus;
    private FloatingActionButton btnToggleMic, btnToggleVideo, btnEndCall, btnSwitchCamera;
    
    private boolean isMuted = false;
    private boolean isVideoOff = false;
    private Camera2Capturer camera2Capturer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_consultation);

        // Get Appointment ID to use as a unique room name
        Intent intent = getIntent();
        if (intent != null) {
            if (intent.hasExtra("appointment_id")) {
                String appointmentId = intent.getStringExtra("appointment_id");
                if (appointmentId != null) {
                    roomName = "Appointment_Room_" + appointmentId;
                }
            }
            if (intent.hasExtra("user_identity")) {
                userIdentity = intent.getStringExtra("user_identity");
            }
        }

        initUI();

        if (checkSelfPermission()) {
            startLocalVideoOnly();
        } else {
            ActivityCompat.requestPermissions(this, REQUESTED_PERMISSIONS, PERMISSION_REQ_ID);
        }
    }

    private void startLocalVideoOnly() {
        tvStatus.setText("Local Preview Mode");
        
        localAudioTrack = LocalAudioTrack.create(this, true, "microphone");
        
        String cameraId = CameraCapturerCompat.getFrontCameraId(this);
        if (cameraId == null) {
            cameraId = CameraCapturerCompat.getBackCameraId(this);
        }
        
        if (cameraId != null) {
            camera2Capturer = new Camera2Capturer(this, cameraId);
            localVideoTrack = LocalVideoTrack.create(this, true, camera2Capturer, "camera");
        }

        if (localVideoTrack != null) {
            // In local-only mode, we can show the user in the main view or keep it in the small preview
            localVideoTrack.addSink(localVideoView);
            Toast.makeText(this, "Camera preview active (Local Mode)", Toast.LENGTH_SHORT).show();
        }
    }

    private void fetchTokenAndConnect() {
        // Placeholder for future API integration
        startLocalVideoOnly();
    }

    private void initUI() {
        localVideoView = findViewById(R.id.localVideoView);
        remoteVideoView = findViewById(R.id.remoteVideoView);
        tvStatus = findViewById(R.id.tvStatus);
        btnToggleMic = findViewById(R.id.btnToggleMic);
        btnToggleVideo = findViewById(R.id.btnToggleVideo);
        btnEndCall = findViewById(R.id.btnEndCall);
        btnSwitchCamera = findViewById(R.id.btnSwitchCamera);

        btnToggleMic.setOnClickListener(v -> toggleMic());
        btnToggleVideo.setOnClickListener(v -> toggleVideo());
        btnEndCall.setOnClickListener(v -> disconnect());
        btnSwitchCamera.setOnClickListener(v -> switchCamera());

        // Mirror the local camera for a more natural feel
        localVideoView.setMirror(true);
    }

    private boolean checkSelfPermission() {
        return ContextCompat.checkSelfPermission(this, REQUESTED_PERMISSIONS[0]) == PackageManager.PERMISSION_GRANTED &&
                ContextCompat.checkSelfPermission(this, REQUESTED_PERMISSIONS[1]) == PackageManager.PERMISSION_GRANTED;
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == PERMISSION_REQ_ID) {
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED && grantResults[1] == PackageManager.PERMISSION_GRANTED) {
                startLocalVideoOnly();
            } else {
                Toast.makeText(this, "Camera and Microphone permissions are required", Toast.LENGTH_LONG).show();
                finish();
            }
        }
    }

    private void connectToRoom() {
        localAudioTrack = LocalAudioTrack.create(this, true, "microphone");
        
        String cameraId = CameraCapturerCompat.getFrontCameraId(this);
        if (cameraId == null) {
            cameraId = CameraCapturerCompat.getBackCameraId(this);
        }
        
        if (cameraId != null) {
            camera2Capturer = new Camera2Capturer(this, cameraId);
            localVideoTrack = LocalVideoTrack.create(this, true, camera2Capturer, "camera");
        }

        if (localVideoTrack != null) {
            localVideoTrack.addSink(localVideoView);
        }

        ConnectOptions connectOptions = new ConnectOptions.Builder(accessToken)
                .roomName(roomName)
                .audioTracks(Collections.singletonList(localAudioTrack))
                .videoTracks(Collections.singletonList(localVideoTrack))
                .build();

        room = Video.connect(this, connectOptions, roomListener());
        tvStatus.setText("Connecting to room: " + roomName);
    }

    private Room.Listener roomListener() {
        return new Room.Listener() {
            @Override
            public void onConnected(@NonNull Room room) {
                tvStatus.setText("Connected");
                // Check if any participants are already in the room
                for (RemoteParticipant remoteParticipant : room.getRemoteParticipants()) {
                    addRemoteParticipant(remoteParticipant);
                    break;
                }
            }

            @Override
            public void onConnectFailure(@NonNull Room room, @NonNull TwilioException e) {
                tvStatus.setText("Connection failed. Check your Token.");
                Toast.makeText(VideoConsultationActivity.this, "Twilio Error: " + e.getMessage(), Toast.LENGTH_LONG).show();
            }

            @Override
            public void onDisconnected(@NonNull Room room, TwilioException e) {
                tvStatus.setText("Disconnected");
                finish();
            }

            @Override
            public void onParticipantConnected(@NonNull Room room, @NonNull RemoteParticipant remoteParticipant) {
                addRemoteParticipant(remoteParticipant);
            }

            @Override
            public void onParticipantDisconnected(@NonNull Room room, @NonNull RemoteParticipant remoteParticipant) {
                removeRemoteParticipant(remoteParticipant);
            }

            @Override public void onReconnecting(@NonNull Room room, @NonNull TwilioException e) {
                tvStatus.setText("Reconnecting...");
            }
            @Override public void onReconnected(@NonNull Room room) {
                tvStatus.setText("Connected");
            }
            @Override public void onRecordingStarted(@NonNull Room room) {}
            @Override public void onRecordingStopped(@NonNull Room room) {}
        };
    }

    private void addRemoteParticipant(RemoteParticipant remoteParticipant) {
        tvStatus.setVisibility(View.GONE);
        remoteParticipant.setListener(remoteParticipantListener());

        // Check for tracks already published by the participant
        for (RemoteVideoTrackPublication videoTrackPublication : remoteParticipant.getRemoteVideoTracks()) {
            if (videoTrackPublication.isTrackSubscribed()) {
                RemoteVideoTrack remoteVideoTrack = videoTrackPublication.getRemoteVideoTrack();
                if (remoteVideoTrack != null) {
                    remoteVideoTrack.addSink(remoteVideoView);
                }
            }
        }
    }

    private void removeRemoteParticipant(RemoteParticipant remoteParticipant) {
        tvStatus.setVisibility(View.VISIBLE);
        tvStatus.setText("Participant disconnected");
    }

    private RemoteParticipant.Listener remoteParticipantListener() {
        return new RemoteParticipant.Listener() {
            @Override public void onAudioTrackPublished(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteAudioTrackPublication remoteAudioTrackPublication) {}
            @Override public void onAudioTrackUnpublished(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteAudioTrackPublication remoteAudioTrackPublication) {}
            @Override public void onAudioTrackSubscribed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteAudioTrackPublication remoteAudioTrackPublication, @NonNull RemoteAudioTrack remoteAudioTrack) {}
            @Override public void onAudioTrackSubscriptionFailed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteAudioTrackPublication remoteAudioTrackPublication, @NonNull TwilioException twilioException) {}
            @Override public void onAudioTrackUnsubscribed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteAudioTrackPublication remoteAudioTrackPublication, @NonNull RemoteAudioTrack remoteAudioTrack) {}
            @Override public void onAudioTrackEnabled(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteAudioTrackPublication remoteAudioTrackPublication) {}
            @Override public void onAudioTrackDisabled(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteAudioTrackPublication remoteAudioTrackPublication) {}
            
            @Override public void onVideoTrackPublished(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteVideoTrackPublication remoteVideoTrackPublication) {}
            @Override public void onVideoTrackUnpublished(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteVideoTrackPublication remoteVideoTrackPublication) {}
            @Override public void onVideoTrackSubscribed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteVideoTrackPublication remoteVideoTrackPublication, @NonNull RemoteVideoTrack remoteVideoTrack) {
                // IMPORTANT: This makes the remote video visible
                remoteVideoTrack.addSink(remoteVideoView);
            }
            @Override public void onVideoTrackSubscriptionFailed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteVideoTrackPublication remoteVideoTrackPublication, @NonNull TwilioException twilioException) {}
            @Override public void onVideoTrackUnsubscribed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteVideoTrackPublication remoteVideoTrackPublication, @NonNull RemoteVideoTrack remoteVideoTrack) {
                remoteVideoTrack.removeSink(remoteVideoView);
            }
            @Override public void onVideoTrackEnabled(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteVideoTrackPublication remoteVideoTrackPublication) {}
            @Override public void onVideoTrackDisabled(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteVideoTrackPublication remoteVideoTrackPublication) {}
            
            @Override public void onDataTrackPublished(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteDataTrackPublication remoteDataTrackPublication) {}
            @Override public void onDataTrackUnpublished(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteDataTrackPublication remoteDataTrackPublication) {}
            @Override public void onDataTrackSubscribed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteDataTrackPublication remoteDataTrackPublication, @NonNull RemoteDataTrack remoteDataTrack) {}
            @Override public void onDataTrackSubscriptionFailed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteDataTrackPublication remoteDataTrackPublication, @NonNull TwilioException twilioException) {}
            @Override public void onDataTrackUnsubscribed(@NonNull RemoteParticipant remoteParticipant, @NonNull RemoteDataTrackPublication remoteDataTrackPublication, @NonNull RemoteDataTrack remoteDataTrack) {}
        };
    }

    private void toggleMic() {
        if (localAudioTrack != null) {
            isMuted = !isMuted;
            localAudioTrack.enable(!isMuted);
            btnToggleMic.setImageResource(isMuted ? R.drawable.ic_mic_off : R.drawable.ic_mic_on);
            btnToggleMic.setSupportBackgroundTintList(android.content.res.ColorStateList.valueOf(
                    isMuted ? getResources().getColor(R.color.emergency_red) : getResources().getColor(R.color.white)));
            btnToggleMic.setSupportImageTintList(android.content.res.ColorStateList.valueOf(
                    isMuted ? getResources().getColor(R.color.white) : getResources().getColor(R.color.primary_dark_brand)));
        }
    }

    private void toggleVideo() {
        if (localVideoTrack != null) {
            isVideoOff = !isVideoOff;
            localVideoTrack.enable(!isVideoOff);
            btnToggleVideo.setImageResource(isVideoOff ? R.drawable.ic_video_off : R.drawable.ic_video_on);
            btnToggleVideo.setSupportBackgroundTintList(android.content.res.ColorStateList.valueOf(
                    isVideoOff ? getResources().getColor(R.color.emergency_red) : getResources().getColor(R.color.white)));
            btnToggleVideo.setSupportImageTintList(android.content.res.ColorStateList.valueOf(
                    isVideoOff ? getResources().getColor(R.color.white) : getResources().getColor(R.color.primary_dark_brand)));
        }
    }

    private void switchCamera() {
        if (camera2Capturer != null) {
            String currentCameraId = camera2Capturer.getCameraId();
            String frontCameraId = CameraCapturerCompat.getFrontCameraId(this);
            String backCameraId = CameraCapturerCompat.getBackCameraId(this);
            
            String newCameraId = null;
            if (currentCameraId.equals(frontCameraId)) {
                newCameraId = backCameraId;
            } else {
                newCameraId = frontCameraId;
            }
            
            if (newCameraId != null) {
                camera2Capturer.switchCamera(newCameraId);
            }
        }
    }

    private void disconnect() {
        if (room != null) room.disconnect();
        if (localAudioTrack != null) localAudioTrack.release();
        if (localVideoTrack != null) localVideoTrack.release();
        finish();
    }

    @Override
    protected void onDestroy() {
        disconnect();
        super.onDestroy();
    }
}
